In [1]:
import pandas as pd

df=pd.read_csv('salez.csv')
df.head(5)

         Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  618.0  South
4  2023-01-05  Product3  501.0   East

In [2]:
df.describe()

            Sales
count   19.000000
mean   554.000000
std    231.543372
min    124.000000
25%    381.500000
50%    554.000000
75%    737.500000
max    868.000000

In [3]:
df.dtypes

Date        object
Product     object
Sales      float64
Region      object
dtype: object

In [8]:
## Handling Missing Values

df.isnull().any()

Date       False
Product    False
Sales       True
Region     False
dtype: bool

In [9]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
11     True
12     True
13    False
14    False
15    False
16     True
17     True
18    False
19    False
20     True
21    False
22    False
23    False
24    False
dtype: bool

In [10]:
df.isnull().sum()

Date       0
Product    0
Sales      6
Region     0
dtype: int64

In [ ]:
df.fillna(0)

          Date   Product  Sales Region
0   2023-01-01  Product3  738.0   West
1   2023-01-02  Product2  868.0  North
2   2023-01-03  Product2  554.0   West
3   2023-01-04  Product1  618.0  South
4   2023-01-05  Product3  501.0   East
5   2023-01-06  Product1    0.0   West
6   2023-01-07  Product3  339.0  South
7   2023-01-08  Product3  280.0  South
8   2023-01-09  Product2  806.0  North
9   2023-01-10  Product2  816.0  South
10  2023-01-11  Product3  469.0   West
11  2023-01-12  Product3    0.0   East
12  2023-01-13  Product3    0.0   East
13  2023-01-14  Product3  676.0   East
14  2023-01-15  Product1  183.0  South
15  2023-01-16  Product1  424.0  South
16  2023-01-17  Product1    0.0  South
17  2023-01-18  Product1    0.0  South
18  2023-01-19  Product2  124.0  North
19  2023-01-20  Product3  732.0   West
20  2023-01-21  Product2    0.0   West
21  2023-01-22  Product3  296.0   West
22  2023-01-23  Product2  737.0   West
23  2023-01-24  Product3  531.0   East
24  2023-01-25  Product2  834.0  North

In [ ]:
## FIlling missing values with mean of the coloumn

In [ ]:
df['Sales_fillNA']=df['Sales'].fillna(df['Sales'].mean())
df
## Not A Number (NAN) => Fill mean of data there

          Date   Product  Sales Region  Sales_fillNA
0   2023-01-01  Product3  738.0   West         738.0
1   2023-01-02  Product2  868.0  North         868.0
2   2023-01-03  Product2  554.0   West         554.0
3   2023-01-04  Product1  618.0  South         618.0
4   2023-01-05  Product3  501.0   East         501.0
5   2023-01-06  Product1    NaN   West         554.0
6   2023-01-07  Product3  339.0  South         339.0
7   2023-01-08  Product3  280.0  South         280.0
8   2023-01-09  Product2  806.0  North         806.0
9   2023-01-10  Product2  816.0  South         816.0
10  2023-01-11  Product3  469.0   West         469.0
11  2023-01-12  Product3    NaN   East         554.0
12  2023-01-13  Product3    NaN   East         554.0
13  2023-01-14  Product3  676.0   East         676.0
14  2023-01-15  Product1  183.0  South         183.0
15  2023-01-16  Product1  424.0  South         424.0
16  2023-01-17  Product1    NaN  South         554.0
17  2023-01-18  Product1    NaN  South         554.0
18  2023-01-19  Product2  124.0  North         124.0
19  2023-01-20  Product3  732.0   West         732.0
20  2023-01-21  Product2    NaN   West         554.0
21  2023-01-22  Product3  296.0   West         296.0
22  2023-01-23  Product2  737.0   West         737.0
23  2023-01-24  Product3  531.0   East         531.0
24  2023-01-25  Product2  834.0  North         834.0

In [15]:
df.dtypes

Date             object
Product          object
Sales           float64
Region           object
Sales_fillNA    float64
dtype: object

In [ ]:
## Renaming the coloumns
df=df.rename(columns={'Date':'Sales Date'}) # Key value pair
df.head()

   Sales Date   Product  Sales Region  Sales_fillNA
0  2023-01-01  Product3  738.0   West         738.0
1  2023-01-02  Product2  868.0  North         868.0
2  2023-01-03  Product2  554.0   West         554.0
3  2023-01-04  Product1  618.0  South         618.0
4  2023-01-05  Product3  501.0   East         501.0

In [26]:
import pandas as pd

df = pd.read_csv('dataz.csv')

df['Value_new']=df['Value'].fillna(df['Value'].mean()).astype(int)

# Preview the DataFrame
df.head()

         Date Category  Value   Product  Sales Region  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         28
1  2023-01-02        B   39.0  Product3  110.0  North         39
2  2023-01-03        C   32.0  Product2  398.0   East         32
3  2023-01-04        B    8.0  Product1  522.0   East          8
4  2023-01-05        B   26.0  Product3  869.0  North         26

In [34]:
df['New Value']=df['Value'].apply(lambda x:x**2)
df.head()

         Date Category  Value   Product  Sales Region  Value_new  New Value
0  2023-01-01        A   28.0  Product1  754.0   East         28      784.0
1  2023-01-02        B   39.0  Product3  110.0  North         39     1521.0
2  2023-01-03        C   32.0  Product2  398.0   East         32     1024.0
3  2023-01-04        B    8.0  Product1  522.0   East          8       64.0
4  2023-01-05        B   26.0  Product3  869.0  North         26      676.0

In [38]:
# Grouping the DataFrame 'df' by the 'Product' column
# This creates groups based on unique values in the 'Product' column
grouped_mean = df.groupby('Product')['Value'].mean()

# The above line calculates the mean (average) of the 'Value' column for each group of 'Product'
# Essentially, it's aggregating the data by 'Product' and computing the average of 'Value' for each product

# Printing the result which shows the mean of 'Value' for each unique 'Product'
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [40]:
df.groupby(['Product','Region'])['Value'].sum()

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [41]:
df.groupby(['Product','Region'])['Value'].mean()

Product   Region
Product1  East      41.714286
          North      4.500000
          South     50.000000
          West      82.000000
Product2  East      28.000000
          North     63.500000
          South     60.333333
          West      53.500000
Product3  East      50.500000
          North     40.600000
          South     71.666667
          West      62.166667
Name: Value, dtype: float64

In [43]:
## Aggregate Multiple functions
grouped_agg=df.groupby('Region')['Value'].agg(['mean','sum','count'])
grouped_agg

             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17

In [ ]:
## Merging and joining Dataframes
df1=pd.DataFrame({'Key':['A','B','C'], 'Value1':[1,2,3]})
df2=pd.DataFrame({'Key':['A','B','D'], 'Value2':[4,5,6]})

df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [ ]:
## Merge Dataframe on the 'Key Coloumns'
pd.merge(df1,df2,on="Key",how="inner")
# on=which coloumn, and based on matching between Keys, inner joins happens

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [ ]:
pd.merge(df1,df2,on="Key",how="outer")
# for "outer", for the dataframe will be considered
#since Value2 doesnt have value for C so NAN and same goes for D in Value1

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [ ]:
pd.merge(df1,df2,on="Key",how="left")
# left outer join => left DF will be given more priority (df1)

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [51]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6