In [ ]:
## Series
## A Pandas Series is a one-dimensional array-like object that
## can hold any data type. It is similar to a column in a table.

In [1]:
import pandas as pd
data=[1,2,3,4,5,6]
series=pd.Series(data)

print("Series:\n",series)

Series:
 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [2]:
## Create a series from dictionary
data={'a':1,'b':2,'c':3}
dict_series=pd.Series(data)
print(dict_series)

a    1
b    2
c    3
dtype: int64

In [3]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [4]:
## Dataframe
## Create a Dataframe from a dictionary of list

data={
    'Name':['Sho','Yo','Wo'],
    'Age':[23,56,78],
    'City':['Mumbai','Bilaspur','Raipur']
}

df=pd.DataFrame(data)
print(df)
print(type(df))

  Name  Age      City
0  Sho   23    Mumbai
1   Yo   56  Bilaspur
2   Wo   78    Raipur
<class 'pandas.core.frame.DataFrame'>

In [6]:
import numpy as np
np.array(df)

array([['Sho', 23, 'Mumbai'],
       ['Yo', 56, 'Bilaspur'],
       ['Wo', 78, 'Raipur']], dtype=object)

In [10]:
## Create a Data from a list of dictionaries

data=[
    {'Name':'Sho','Age':23,'City':'Mumbai'},
    {'Name':'Sho1','Age':22,'City':'Mumbai1'},
    {'Name':'Sho2','Age':24,'City':'Mumbai2'},
    {'Name':'Sho3','Age':25,'City':'Mumbai3'}
]

df=pd.DataFrame(data)
print(df)
print(type(df))

   Name  Age     City
0   Sho   23   Mumbai
1  Sho1   22  Mumbai1
2  Sho2   24  Mumbai2
3  Sho3   25  Mumbai3
<class 'pandas.core.frame.DataFrame'>

In [12]:
df=pd.read_csv('salez.csv')
print(df.head(5))

         Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  618.0  South
4  2023-01-05  Product3  501.0   East

In [13]:
df.tail(5)

          Date   Product  Sales Region
20  2023-01-21  Product2    NaN   West
21  2023-01-22  Product3  296.0   West
22  2023-01-23  Product2  737.0   West
23  2023-01-24  Product3  531.0   East
24  2023-01-25  Product2  834.0  North

In [14]:
## Accessing data from Dataframe
df

          Date   Product  Sales Region
0   2023-01-01  Product3  738.0   West
1   2023-01-02  Product2  868.0  North
2   2023-01-03  Product2  554.0   West
3   2023-01-04  Product1  618.0  South
4   2023-01-05  Product3  501.0   East
5   2023-01-06  Product1    NaN   West
6   2023-01-07  Product3  339.0  South
7   2023-01-08  Product3  280.0  South
8   2023-01-09  Product2  806.0  North
9   2023-01-10  Product2  816.0  South
10  2023-01-11  Product3  469.0   West
11  2023-01-12  Product3    NaN   East
12  2023-01-13  Product3    NaN   East
13  2023-01-14  Product3  676.0   East
14  2023-01-15  Product1  183.0  South
15  2023-01-16  Product1  424.0  South
16  2023-01-17  Product1    NaN  South
17  2023-01-18  Product1    NaN  South
18  2023-01-19  Product2  124.0  North
19  2023-01-20  Product3  732.0   West
20  2023-01-21  Product2    NaN   West
21  2023-01-22  Product3  296.0   West
22  2023-01-23  Product2  737.0   West
23  2023-01-24  Product3  531.0   East
24  2023-01-25  Product2  834.0  North

In [15]:
df['Date']

0     2023-01-01
1     2023-01-02
2     2023-01-03
3     2023-01-04
4     2023-01-05
5     2023-01-06
6     2023-01-07
7     2023-01-08
8     2023-01-09
9     2023-01-10
10    2023-01-11
11    2023-01-12
12    2023-01-13
13    2023-01-14
14    2023-01-15
15    2023-01-16
16    2023-01-17
17    2023-01-18
18    2023-01-19
19    2023-01-20
20    2023-01-21
21    2023-01-22
22    2023-01-23
23    2023-01-24
24    2023-01-25
Name: Date, dtype: object

In [16]:
type(df['Date'])

pandas.core.series.Series

In [17]:
## For row indices: loc[0]
## For coloumn indices: iloc[0]

df.loc[0][0]

C:\Users\OMEN\AppData\Local\Temp\ipykernel_4496\2945265578.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'2023-01-01'

In [20]:
## ACCESSING A SPECIFIC ELEMENT

df.at[1,'Product']

'Product2'

In [22]:
## ACCESSING A SPECIFIC ELEMENT USING iat
df.iat[0,0]

'2023-01-01'

In [48]:
import pandas as pd

# Create a sample DataFrame
df = pd.DataFrame({
    'Product': ['A', 'B', 'C'],
    'Sales': [20000, 25000, 30000]
})

# Add a new column
df['Profit'] = [5000, 6000, 7000]

print("Original DataFrame:")
print(df)

# Remove a column
df.drop('Profit', axis=1, inplace=True)

print("\nDataFrame after removing 'Profit':")
print(df)

Original DataFrame:
  Product  Sales  Profit
0       A  20000    5000
1       B  25000    6000
2       C  30000    7000

DataFrame after removing 'Profit':
  Product  Sales
0       A  20000
1       B  25000
2       C  30000

In [49]:
df['Sales']=df['Sales']+2000
df

  Product  Sales
0       A  22000
1       B  27000
2       C  32000

In [50]:
df.drop(0)

  Product  Sales
1       B  27000
2       C  32000

In [ ]:
df.drop(0,inplace=True) ## Permanent removal

In [ ]:
df.describe() ## Statistical summary

              Sales
count      2.000000
mean   29500.000000
std     3535.533906
min    27000.000000
25%    28250.000000
50%    29500.000000
75%    30750.000000
max    32000.000000